[package]
name = "databend-common-expression"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
test = true

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-flight = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
async-backtrace = { workspace = true }
base64 = "0.21.0"
borsh = { workspace = true, features = ["derive"] }
bumpalo = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
comfy-table = "6"
dashmap = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-ast = { workspace = true }
databend-common-base = { workspace = true }
databend-common-datavalues = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-geobuf = { workspace = true }
databend-common-hashtable = { workspace = true }
databend-common-io = { workspace = true }
educe = "0.4"
enum-as-inner = "0.5"
ethnum = { workspace = true, features = ["serde", "macros", "borsh"] }
futures = { workspace = true }
geo = { workspace = true }
geoarrow = { git = "https://github.com/geoarrow/geoarrow-rs" }
geos = { workspace = true }
geozero = { workspace = true }
hex = "0.4.3"
itertools = { workspace = true }
jsonb = { workspace = true }
lexical-core = "0.8.5"
log = { workspace = true }
match-template = { workspace = true }
memchr = { version = "2", default-features = false }
micromarshal = "0.5.0"
num-bigint = "0.4.6"
num-traits = "0.2.15"
ordered-float = { workspace = true, features = ["serde", "rand", "borsh"] }
parquet.workspace = true
rand = { workspace = true }
recursive = "0.1.1"
roaring = { version = "0.10.1", features = ["serde"] }
rust_decimal = "1.26"
serde = { workspace = true }
serde_json = { workspace = true }
simdutf8 = "0.1.4"
strength_reduce = "0.2.4"
terminal_size = "0.2.6"
tokio = { workspace = true }
tonic = { workspace = true }
typetag = { workspace = true }
unicode-segmentation = "1.10.1"

[dev-dependencies]
arrow-ord = { workspace = true }
goldenfile = "1.4"
pretty_assertions = "1.3.0"
rand = { workspace = true }
rmp-serde = "1.1.1"

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["geos"]
