[package]
name = "databend-common-formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
aho-corasick = { version = "1.0.1" }
async-trait = { workspace = true }
base64 = "0.21.0"
bstr = "1.0.1"
chrono-tz = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-io = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-settings = { workspace = true }
databend-storages-common-blocks = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
geo = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
hex = "0.4.3"
jsonb = { workspace = true }
lexical-core = "0.8.5"
match-template = { workspace = true }
micromarshal = "0.7.0"
num = "0.4.0"
num-traits = "0.2.15"
ordered-float = { workspace = true }
roaring = { version = "0.10.1", features = ["serde"] }
serde_json = { workspace = true }

[dev-dependencies]
databend-common-arrow = { workspace = true }
pretty_assertions = "1.3.0"
tokio = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["geos", "match-template"]
